import GlobalMap from "components/homePage/GlobalMap";
import HeroSection from "components/homePage/HeroSection";
import Head from "next/head";

export default function Home() {
	return (
		<>
			<Head>
				<title>Oro Capital - Invest Safe Invest ORO</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<HeroSection />
			<GlobalMap />
		</>
	);
}
